### ISSUE TITLE
Space between paragraphs are huge. 

### ISSUE THREAD

**Issue by tasomaniac** [gdg-x/hub#46] opened 2015-09-01 14:09 UTC
The space between paragraphs seems to be lot bigger than the ones in Google+ and Google Developers page for the events. Here is one screenshot. 

![image](https://cloud.githubusercontent.com/assets/763339/9606449/26b564ca-50cc-11e5-8678-16102a575752.png)

**Comment by Splaktar** [comment] 2015-09-01 23:30
Looks like a duplicate of #12

**Comment by tasomaniac** [comment] 2015-09-02 06:40
Oh sorry. I made a quick search and couldn't find it.

**Closed as completed** 2015-09-02 06:41 UTC
Labels: bug
